### ISSUE TITLE
Reduce clicks needed to see map/graph selections

### ISSUE THREAD

**Issue by sarahcd** [movestore/MorningReport#7]
I haven't tested this user feedback in detail. They report they'd like to see the voltage of active tags, and were able to do it in the output, but it required a lot of clicks. This might already be possible by saving the selections in RShiny for future runs.

**Comment by annescharf** [comment]
@sarahcd you mean that in the second tab "visualization" by default the 1st or 2nd plot shows de tag voltage? 
This is not possible because every tag type will have a different column name refering to voltage so there is no way we can make a general default for this.
But once selected, and by clicking "store settings" than the settings will remain for future runs

**Comment by annescharf** [comment]
A quick overview of a specific attribute, ie voltage, can be obtained using the App "[Morning Report Attribute Plots PDF](https://www.moveapps.org/apps/browser/d8c1e383-564b-46f2-a758-20938de20047)"
